# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informasi',
            old_name='position',
            new_name='location',
        ),
    ]
