# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0005_auto_20160814_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contents', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='document/%Y/%m/%d')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
    ]
