# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0006_berita'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='keterangan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
