# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0007_berita_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='sumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
