# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0008_berita_sumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='berita',
            old_name='thumbnail',
            new_name='image',
        ),
    ]
