# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0009_auto_20160820_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='keterangan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
