# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0010_auto_20160821_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berita',
            name='sumber',
            field=models.CharField(blank=True, choices=[('SuaraMerdeka', 'SuaraMerdeka.com'), ('RadarTegal', 'RadarTegal.com')], max_length=40, null=True),
        ),
    ]
