# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0012_auto_20160821_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='informasi',
            name='kategori',
            field=models.CharField(blank=True, choices=[('attractions', 'Tempat Wisata'), ('hotels', 'Penginapan'), ('restaurants', 'Tempat Makan')], max_length=40, null=True),
        ),
    ]
