# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0013_informasi_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informasi',
            name='kategori',
        ),
    ]
