# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 14:20
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0015_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='images',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_logo', to='filer.Image'),
        ),
    ]
