# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-04 20:14
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0016_auto_20160904_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='images',
        ),
        migrations.AddField(
            model_name='informasi',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
