# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0019_informasi_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='checker_runtime',
        ),
        migrations.RemoveField(
            model_name='article',
            name='news_website',
        ),
        migrations.DeleteModel(
            name='Berita',
        ),
        migrations.RemoveField(
            model_name='newswebsite',
            name='scraper',
        ),
        migrations.RemoveField(
            model_name='newswebsite',
            name='scraper_runtime',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='NewsWebsite',
        ),
    ]
